### ISSUE TITLE
Code Issue - SQLPageDataProvider.java

### ISSUE THREAD

**Issue by sRajeswari** [xframium/xframium-java#17]
at Line 111
                boolean lockRecords = "Y".equals( (String) data[i][1] ) || "1".equals( (String) data[i][3] );

it should be
                boolean lockRecords = "Y".equals( (String) data[i][1] ) || "1".equals( (String) data[i][1] );

**Comment by xframium** [comment]
This has been resolved and part of the 1.0.5 build
