### ISSUE TITLE
Expressive tags for tests

### ISSUE THREAD

**Issue by gregjacobs** [xframium/xframium-java#22]
My one concern for writing tests with the framework is that tests look like a "blur of stuff" when I see only `<step>` tags on every line. I would love to see expressive xml tags for my tests to make them highly readable and maintainable. 

For instance, changing the following:

``` xml
<step page="Login" type="EXISTS" name="LOCATION_ALERT_ALLOW_BTN" failureMode="IGNORE">
    <step page="Login" type="CLICK" name="LOCATION_ALERT_ALLOW_BTN" />
</step>
<step page="Login" type="DEVICE" name="CONTEXT">
    <parameter type="STATIC" value="WEBVIEW_1" />
</step>
<step page="Login" type="WAIT_FOR" name="USERNAME">
    <parameter type="STATIC" value="15" />
</step>
<step page="Login" type="SET" name="USERNAME">
    <parameter type="STATIC" value="user123" />
</step>
<step page="Login" type="SET" name="PASSWORD">
    <parameter type="STATIC" value="Welcome1" />
</step>
<step page="Login" type="CLICK" name="SUBMIT" />
```

into something like the equivalent code below would make them much easier to read and understand:

``` xml
<if-exists page="Login" element="LOCATION_ALERT_ALLOW_BTN">
    <click page="Login" element="LOCATION_ALERT_ALLOW_BTN" />
</if-exists>
<context name="WEBVIEW_1" />
<wait-for page="Login" element="USERNAME" timeout="15">
<set page="Login" element="USERNAME" value="my_user">
<set page="Login" element="PASSWORD" value="my_password">
<click page="Login" element="SUBMIT" />
```

(note the `element` attribute names, which make it clear that they relate to `<element>` tags in the page models)

What do you think?

**Comment by gregjacobs** [comment]
Btw, where I said "my only concern" at the top, I meant that I love everything else about xframium so far!

**Comment by xframium** [comment]
There are pieces being worked on to help with the XML framework and its format.  There will be a version 2 of the schema released but not for a few more versions.  Closing for now
