### ISSUE TITLE
Add <function> to <page> objects

### ISSUE THREAD

**Issue by gregjacobs** [xframium/xframium-java#23]
Last thought for the day (maybe :)), I would love to be able to attach functions to page objects. These would be functions that could be reused with any tests that work with that page.

``` xml
<page name="Login">
    <element name="USERNAME" value="[track-id='login.username']" descriptor="CSS" />
    <element name="PASSWORD" value="[track-id='login.password']" descriptor="CSS" />
    <element name="SUBMIT"   value="[track-id='login.submit']"   descriptor="CSS" />
    <element name="LOCATION_PROMPT_ALLOW_BTN" value="//UIAButton[@name='Allow']" descriptor="XPATH" />

    <function name="dismissLocationPrompt">
        <step type="EXISTS" name="LOCATION_PROMPT_ALLOW_BTN" failureMode="IGNORE">
            <step type="CLICK" name="LOCATION_PROMPT_ALLOW_BTN" />
        </step>
    </function>
</page>
```

This would also give meaning to the `page` attribute in `<step type="CALL">` 👍

**Comment by xframium** [comment]
Functions can be called from any test element.  After an internal review we feel that this would introduce too much complexity in the page elements.  Feel free to reopen with more details if needed
