### ISSUE TITLE
Java TestName = null

### ISSUE THREAD

**Issue by westondunn** [xframium/xframium-java#26]
When using version 1.0.4 in a Java project, the test name comes across as null.  I have verified the expected functionality by rolling back to 1.0.3 and it worked.  See below:

`@Test( dataProvider = "deviceManager", description = "As a Customer, I want to login to MyAccount from the Login page.")
    public void testLoginPage( TestName testName )
        throws Exception
...`

**Output**:
1.0.4 = 

> INFO: Creating page implementation as pages.spi.LoginImpl
> Sep 19, 2016 9:50:29 PM org.xframium.page.element.SeleniumElement getElement
> INFO: **_null_**.EMPTY-->Microsoft Internet Explorer [Internet Explorer]: Locating element by [XPath] using [//*[@id='UserID']]
> Sep 19, 2016 9:50:29 PM org.xframium.page.element.SeleniumElement getElement

1.03 = 

> INFO: Creating page implementation as pages.spi.LoginImpl
> Sep 19, 2016 9:38:12 PM org.xframium.page.element.SeleniumElement getElement
> INFO: _**LoginTest.testLoginPage**_.EMPTY-->Microsoft Internet Explorer [Internet Explorer]: Locating element by [XPath] using [//*[@id='UserID']]
> Sep 19, 2016 9:38:12 PM org.xframium.page.element.SeleniumElement getElement

![image](https://cloud.githubusercontent.com/assets/1231495/18656047/6cf6682e-7eb3-11e6-9222-059b63c07d95.png)

**Comment by xframium** [comment]
Resolved in 1.0.5 - testName was being forced to null
