### ISSUE TITLE
Issue with configuring BDD

### ISSUE THREAD

**Issue by ManasBBSR** [xframium/xframium-java#28]
Hi,

I was trying to use xFramium for BDD test but not sure how to configure it as the website does not give any example. Could someone please help with a sample of how a BDD Test needs to be written in the test.xml file.

Secondly I think some keywords needs to be added specifically for Selenium tests like selecting a dropdown value & using actions for clicking on menus. I'm a novice in Java hence not able to figure out if xFramium already supports these operations on a desktop based web browser.

Appreciate your support on this.

Thanks,
Manas

**Comment by xframium** [comment]
BDD Test support in xFramium is achieved via the XML framework.  Check http://xframium.org/keyword.html#bdd for documentation and examples

For SELECT lists in web browsers, use the SET keyword passing it wither the value or visible element in the option. see http://xframium.org/keyword.html#kw-set

**Comment by RevathiAV** [comment]
The link which leads to a sample configuration xml gives 404 page not found. could you please check on this 

link:  http://xframium.org/sample/driverConfigBDD.xml

Thanks,
Revathi
