### ISSUE TITLE
Get Selected value from the Dropdown list

### ISSUE THREAD

**Issue by shivajibr** [xframium/xframium-java#32]
Both Attribute and GET keywords are not returning the first selected value. So adding a new switch case in _getValue method in SeleniumElement to handle select elements will solve the issue

switch ( currentElement.getTagName().toUpperCase() )
        {
            case "IMG":
                returnValue = currentElement.getAttribute( "src" );

```
        case "INPUT":
            returnValue = currentElement.getAttribute( "value" );

        case "SELECT"
            returnValue = new Select(currentElement).getFirstSelectedOption().getText();

        default:
            returnValue = currentElement.getText();
    }
```

**Comment by xframium** [comment]
Resolved in 1.0.5
