### ISSUE TITLE
Reports not displayed for the secondary device

### ISSUE THREAD

**Issue by shivajibr** [xframium/xframium-java#34]
When using multiple devices for the same test, report gets generated only for the primary device in the main test report. The report steps for the secondary device are not available in the main report instead they are available as a separate file.

The steps for all the devices used in the test should be made available in the same report

**Comment by xframium** [comment]
This is still under development.  With reporting information being stored in thread local storage it is hard to get access to this data without breaking the current reports

**Comment by xframium** [comment]
The entire reporting subsystem was rewritten for 1.0.7 and this issue has been resolved.  The additional device actions will all appear int he same report with a notation of the alternate device
