### ISSUE TITLE
Switch to window by Index

### ISSUE THREAD

**Issue by shivajibr** [xframium/xframium-java#35]
The Window/Browser keyword handles switching to windows based on Title or URL. But there are some applications that do not have window title or URL's. In these cases we will need to switch to the window based on the index.

A new sub option can be added to Browser keyword to handle this.

**Comment by xframiumAS** [comment]
Added a new switch type SWITCH_WIN_INDEX to navigate to windows

**Comment by xframium** [comment]
added
