### ISSUE TITLE
BeforeMethod is not called, if used with Dataprovider and Groups in Java based approach

### ISSUE THREAD

**Issue by sRajeswari** [xframium/xframium-java#39]
In java based approach, BeforeMethod is not executed, if @Test used with dataprovider and Groups attribute. 
Ex: 
 @Test(dataProvider = "dataManager", groups={"regression"})
public void Test1(String s)
{
    System.out.println(s);
}
@BeforeMethod
public void beforemethod(Method currentMethod, Object[] testArgs)
{
    System.out.println("********_Before Method**_********");
}
@DataProvider ( name = "dataManager", parallel = true)
public Object[][] getData1()
{
    String[][] s=new String[1][1];
    s[0][0]="Test1";
    return s;
}

---

Please include  (alwaysRun=true) in beforeMethod call, as mentioned in the below TestNg issue.

https://github.com/cbeust/testng/issues/378

**Comment by xframium** [comment]
Resolved in 1.0.6
