### ISSUE TITLE
Report format error

### ISSUE THREAD

**Issue by xframiumAS** [xframium/xframium-java#40]
for some of the report properties, the values are not substituted properly as shown below

Verification that the %s element is present on the page %s failed.
%s

corresponding message in outputFormatter.properties is
_KWSExists=Verification that the <span class="elementName">%1%s</span> element is present on the page <span class="pageName">%2%s</span> failed.<br/><span class="fail" style="margin-left: 10px">%3%s</span>

instead it should have been
_KWSExists=Verification that the <span class="elementName">%1$s</span> element is present on the page <span class="pageName">%2$s</span> failed.<br/><span class="fail" style="margin-left: 10px">%3$s</span>

This is the case in most of the properties. should we change for all of them?

**Comment by xframiumAS** [comment]
attribute=Retrieved the value of the attribute <span class="elementName">%3$s</span> on the element <span class="elementName">%2$s</span> on the page <span class="pageName">%1$s</span> as <span class="pass"><b>%4$s</b></span>

The attribute property in outputFormatter.properties is showing incorrect format

"Retrieved the value of the attribute NAME on the element googleindia on the page name as Email" the message should have been
Retrieved the value of the attribute NAME on the element name on the page googleindia as Email"

the property is now corrected to 
attribute=Retrieved the value of the attribute <span class="elementName">%3$s</span> on the element <span class="elementName">%1$s</span> on the page <span class="pageName">%2$s</span> as <span class="pass"><b>%4$s</b></span>

Also, _KWSExists property is changed

**Comment by xframium** [comment]
Resolved in 1.0.6
