### ISSUE TITLE
Keyword for checking enabled/disabled

### ISSUE THREAD

**Issue by shivajibr** [xframium/xframium-java#42]
Need to Implement keyword to check whether WebElement is enabled or disabled. The underlying code implementation will be WebElement.isEnabled() which returns true or false.

Alternate solution of using getAttribute will not work in all cases. If there is no attribute called "enabled" or "disabled" for the WebElement it returns null. Hence the need to implement a different keyword as stated above

**Comment by xframium** [comment]
keyword added
