### ISSUE TITLE
support for mobile emulation in chrome browser

### ISSUE THREAD

**Issue by xframiumAS** [xframium/xframium-java#43]
in chrome options factory, change the below condition from else if to else
else if(name.equalsIgnoreCase("prefs"))

**Comment by xframiumAS** [comment]
The mobile emulation is added to chrome options as per the below code
Map<String, String> mobileEmulation = new HashMap<String, String>();
mobileEmulation.put("deviceName", "Google Nexus 5");

Map<String, Object> chromeOptions = new HashMap<String, Object>();
chromeOptions.put("mobileEmulation", mobileEmulation);
DesiredCapabilities capabilities = DesiredCapabilities.chrome();
capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);

Our deviceRegistry supports objectcapability where this option can be passed as
<device  name="Chrome" os="Windows" browserName="chrome" manufacturer="Google" model="Chrome" active="true">
        <objectCapability name="chrometest">
            <capabilities factoryName="ChromeOptions">
                <options name = "mobileEmulation" key="deviceName">Google Nexus 5</options>  
            </capabilities>  
        </objectCapability>
    </device>

To support this type of formats the code in ChromeOptionsFactory has to be changed from 
else if(name.equalsIgnoreCase("prefs")) to else statement

**Comment by xframium** [comment]
resolved in 1.0.6
