### ISSUE TITLE
Any way to support handling recovery in XML Keyword approach

### ISSUE THREAD

**Issue by shivajibr** [xframium/xframium-java#51]
Any alternate way to support running recovery steps in case of failure before doing a browser close.

One of the examples when running test scripts in Mobile Perfecto cloud, the sessions are not getting closed, we have explicitly run this code snippet

<step name="execjs" page="ClaimList" type="EXECJS">
            <parameter type="STATIC" value="window.close ();"></parameter>
</step>

**Comment by xframium** [comment]
In version 1.7 there will be the ability to run a function when a device is first used in a suite, before a test is run and after a test is run
