### ISSUE TITLE
Restful service with JSON response throwing Classcastexception

### ISSUE THREAD

**Issue by shivajibr** [xframium/xframium-java#52]
On calling a restful service with a JSON response get below class cast exception on processing JSON response

Caused by: java.lang.ClassCastException: net.minidev.json.JSONArray cannot be cast to java.lang.String
	at org.xframium.utility.WebServiceClientUtil.processResult(WebServiceClientUtil.java:544)
	at org.xframium.utility.WebServiceClientUtil.callWebService(WebServiceClientUtil.java:83)
	... 20 more

Below is the sample test against which the error is happening:

<test name="Rest_Get_Test_1" timed="true" active="true">
		   <step name="restservice_getrequest" page="eAgent" type="EXECWS" >
		   		<parameter type="STATIC" name="url" value="https://itunes.apple.com/lookup?id=909253"
                   usage="input" />
                <parameter type="STATIC" name="method" value="GET" usage="input" />
                <parameter type="STATIC" name="media-type" value="text/xml" usage="input" />
     			<parameter type="STATIC" name="type" value="REST" usage="input" />
     			<parameter type="STATIC" name="payload" value="none" usage="input" />
     			<parameter type="STATIC" name="type" value="json" usage="output" />
     			<parameter type="STATIC" name="var1" value="$..resultCount" usage="output" />
		   </step>
		   
		   <step name="restservice_report" page="eAgent" type="REPORT" >		   
		   	<parameter type="CONTEXT" value="var1" />
		   </step>
	       
	</test>

If the below code is type casted then the error goes off

String value = ctx.read( param.path );
contextMap.put( param.name, value );

Changing it to below code has resolved the issue:

JSONArray value = (JSONArray)ctx.read( param.path ); 
contextMap.put( param.name, value.toJSONString() );

**Comment by xframium** [comment]
Resolved
