### ISSUE TITLE
Global Implicit waits will be overridden when using DEVICE> CLEAN (BrowserCacheLogic)

### ISSUE THREAD

**Issue by shivajibr** [xframium/xframium-java#53]
On using Clean option in DEVICE keyword, the Implicit wait setting is overridden, 

We have this setting in driverConfig

# Config for implicit waits
driver.propertyAdapters=org.xframium.device.property.SeleniumPropertyAdapter
selenium.timeouts.implicitWait=60000

On using DEVICE>CLEAN, this value is reset to 0

finally
        {
            switchToContext(driver, currentContext);
            driver.manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
        }

This is for both clearSafariIOSCache and clearChromeAndroidCache

These driver.manage.timeout statements should be removed from these methods and instead have a global setting in driverconfig

**Comment by xframium** [comment]
Resolved
