### ISSUE TITLE
Error on running a test on Android/IOS if app is not pre-installed on the device

### ISSUE THREAD

**Issue by shivajibr** [xframium/xframium-java#54]
When the application is not installed on the device, on running the test scripts we get a DeviceConfigurationException. Below code snippet is checking if the Application is pre-installed, if installed start the application, else throw  an error.

Below is the else block in the code, that is throwing up error. When we do end to end automation through Jenkins this becomes an issue having an expectation application has to be pre-instllaed

if( ApplicationRegistry.instance().getAUT() != null && ApplicationRegistry.instance().getAUT().getAppleIdentifier() != null && !ApplicationRegistry.instance().getAUT().getAppleIdentifier().isEmpty() )
            {
			    if ( ( (IOSDriver) webDriver.getNativeDriver() ).isAppInstalled( ApplicationRegistry.instance().getAUT().getAppleIdentifier() ) )
			    {
    			    log.warn( "Attempting to start " + ApplicationRegistry.instance().getAUT().getAppleIdentifier() );
                    CloudActionProvider actionProvider = (CloudActionProvider) Class.forName( CloudActionProvider.class.getPackage().getName() + "." + useCloud.getProvider() + "CloudActionProvider" ).newInstance();
                    actionProvider.startApp( caps.getCapability( "executionId" ) + "", caps.getCapability( "deviceName" ) + "", ApplicationRegistry.instance().getAUT().getName(), ApplicationRegistry.instance().getAUT().getAppleIdentifier() );
			    }
			    **else
			        throw new DeviceConfigurationException( ApplicationRegistry.instance().getAUT().getAppleIdentifier() );**
			    
			    String interruptString = ApplicationRegistry.instance().getAUT().getCapabilities().get( "deviceInterrupts" )  != null ? (String)ApplicationRegistry.instance().getAUT().getCapabilities().get( "deviceInterrupts" ) : DeviceManager.instance().getDeviceInterrupts();
	            webDriver.setDeviceInterrupts( getDeviceInterrupts( interruptString, webDriver.getExecutionId(), webDriver.getDeviceName() ) );
            }

**Expected behavior:** 
The else condition should not be there. Even if the application is not installed, the script should not throw an error, the installation should be handled through the keywords. Below else code should be removed in both AndroidDeviceFactory and IOSDeviceFactory

**else
			        throw new DeviceConfigurationException( ApplicationRegistry.instance().getAUT().getAppleIdentifier() );**

**Comment by xframium** [comment]
This is the correct behavior.  If you specify an application during the test run it is expected to be installed.  Use the NOOP application to start the device without any application installed
