### ISSUE TITLE
Loop Keyword only looping at one data level

### ISSUE THREAD

**Issue by ghost** [xframium/xframium-java#56]
Currently the loop keyword only allows looping at one data level...

				    // This is a context table from the current record - we only go 1 level deep now
				    //
				    tableName = tableName.substring( 1 );
				    String[] valueSet = tableName.split( "\\." );
				    if ( valueSet.length == 2 )
Would it be possible to increase this to n level rather than restricting it to one level of depth

ie looping through data at source1.level1.level2, source1.level1.level2.level3 etc....

**Comment by xframium** [comment]
Scheduled for the 1.0.8 release

**Comment by ghost** [comment]
Hi

Do we know if this has made it in for the 1.0.8 release?

Paul

**Comment by allengeary** [comment]
This has been implemented - there is an example in the testing project
