### ISSUE TITLE
Compare issue - Step appearing as failed and giving a wrong view of the test execution.

### ISSUE THREAD

**Issue by ManasBBSR** [xframium/xframium-java#57]
I want to validate the data from the page data as UserGroup= Employee. The below else condition is executing but the steps for the upper one is showing as Failed even though we are executing with failureMode as IGNORE.
essential we need to use Switch Case. means if we have more than 3 data then we can go swichcase keyword.
Please have a look into below function withresult.

<function name="AASelectUserGroup">
	<step type="COMPARE" name="existsCompare" page="Login" failureMode="IGNORE">
		<parameter value="Broker" type="STATIC"></parameter>
		<parameter value="GWSession.UserGroup" type="DATA"></parameter>
		<step type="CLICK" name="lnk_Broker" page="Login"></step>
		
		<step type="ELSE" name="elseCondition" page="Login">
			<parameter value="Employee" type="STATIC"></parameter>
			<parameter value="GWSession.UserGroup" type="DATA"></parameter>
			<step type="CLICK" name="lnk_Employee" page="Login"></step>
		</step>
	</step>
</function>

![image](https://cloud.githubusercontent.com/assets/11156407/21104317/19539420-c054-11e6-99f0-9cec4e3ffada.png)

**Comment by xframium** [comment]
The underlying reporting subsystem has undergone a major overhaul for the 1.0.7 release.  This issue has been addressed
