### ISSUE TITLE
Debugger artifact not able to be disabled

### ISSUE THREAD

**Issue by westondunn** [xframium/xframium-java#58]
When trying to disable the debugger without commenting out the code, the active attribute set to false does not work.

`<driver type="WEB" outputFolder="test-output" displayResults="true" cachingEnabled="true">`
     ` <artifact active="false" type="DEBUGGER"/>`
`</driver>`

**Comment by xframium** [comment]
This has been resolved in the latest version of the driver and will be available in the 1.0.8 release
