### ISSUE TITLE
Not able to open Reports after test completion

### ISSUE THREAD

**Issue by sumanamuppala** [xframium/xframium-java#61]
Hi 
iam sumana ,i work in Gm financial 
i use xframium framework (XML keyword)for our test automation 
and once i run my test and fails or passes reports are not opening in browser 
Can you Please take a look  

Thank you 
Sumana

**Comment by westondunn** [comment]
There were a few reasons I have seen for this:

1. When a filter is set to hide the 'test-output' folder in Eclipse of your working set
2. Network was blocking us from pulling the 'Angular' assets (RESOLVED)
3. 'displayResults' is set to 'false'
4. 1.0.6 had some major reporting issues (RESOLVED in later releases)
