### ISSUE TITLE
Debugging of xFramium tests.

### ISSUE THREAD

**Issue by ManasBBSR** [xframium/xframium-java#64]
Hi Team,

Could you please let me know how to debug a test step by step in xFramium and not on the basis of keyword. I tried the xFramium debugger which launches the debugger in the browser but I'm not able to control the execuion.

Thanks & Regards,
Manas Ranjan Sahu

**Comment by allengeary** [comment]
Please open a group discussion

https://groups.google.com/forum/#!forum/xframium
