### ISSUE TITLE
Handling of Dynamic web tables and iterating through row & columns of a web table.

### ISSUE THREAD

**Issue by ManasBBSR** [xframium/xframium-java#65]
Hi Team,

Do we have any keyword to iterate over the values of a web table and secondly handling dynamic web table within which there are multiple types of webelement that might include inputbox, dropdown, date fields etc. in the table with elements having generated id's. 

Thanks & Regards,
Manas

**Comment by allengeary** [comment]
Please open a group discussion

https://groups.google.com/forum/#!forum/xframium
