### ISSUE TITLE
Keyword for extracting data from screen and updating an excel workbook

### ISSUE THREAD

**Issue by ManasBBSR** [xframium/xframium-java#66]
Hi Team,

Is there a way by which we can extract data from the application under test and put it an excel for later reference.

Thanks & Regards,
Manas

**Comment by allengeary** [comment]
This was added to the REPORT keyword.  Adding ADD_TO_CSV to the report keyword and adding the ADD_TO_CSV artifact will get you the desired result.  Check the online documentation for REPORT
