### ISSUE TITLE
Capturing screen output and storing in excel spreadsheet.

### ISSUE THREAD

**Issue by ManasBBSR** [xframium/xframium-java#67]
Hi Team,

We have a requirement where we have to capture the output of a particular test from the screen and put the data into an excel sheet which would be used for validation by SME's. Do we have any keyword which would help in this aspect.

Thanks & Regards,
Manas

**Comment by allengeary** [comment]
Manas,

Please use the discussion group for things like this.  This is for logging bugs.

In answer to your question you can use the REPORT keyword and specify ADD_TO_CSV as a parameter.  That is available in 1.0.8
