### ISSUE TITLE
String CONCAT - Issue appending to original value

### ISSUE THREAD

**Issue by shivajibr** [xframium/xframium-java#68]
case CONCAT:
                StringBuilder buff = new StringBuilder( originalValue );
                for( int i = 0; i < paramCount; ++i )
                {
                    buff.append( getParameterValue( getParameterList().get( i ), contextMap, dataMap ) + "" );
                }
                newValue = buff.toString();
                break;

Here in the above code the for loop should start from i=1. With i=0, original value passed as a parameter will also get appended again.

**Comment by allengeary** [comment]
Are you referring to STRING or STRING2.  For STRING2 that is the expected behavior.  There is no need for an "original value" as it will CONCAT all parameters together.
