### ISSUE TITLE
Absolute path for "View XML" link

### ISSUE THREAD

**Issue by wonderful4228** [xframium/xframium-java#69]
HI Allen,

I found an issue when click "View XML" link, it does not have any reaction and I found the file path is absolute to "C://User/Allen/git...."

![capture](https://cloud.githubusercontent.com/assets/4716942/23109805/15912d54-f757-11e6-9aba-4d33e9756e2a.PNG)

**Comment by xframium** [comment]
The artifact sub-system was redesigned with 1.0.10.  This issue has been resolved
