### ISSUE TITLE
xframium-serialization maven repository is missing

### ISSUE THREAD

**Issue by JocelynLiu** [xframium/xframium-java#72]
Could anyone please have a look if this maven repository is missing or relocated?  
This is a blocker to new user, without the package of com.xframium.serialization.*, nothing works.

```
   <dependency>
      <groupId>com.xframium</groupId>
      <artifactId>xframium-serialization</artifactId>
      <version>2.0.6</version>
    </dependency>
```

**Comment by allengeary** [comment]
Do you have the repository added as:
<repository>
  <id>xframium</id>
  <name>xFramium</name>
  <url>http://www.xframium.org/repository</url>
  <snapshots>
    <enabled>true</enabled>
    <updatePolicy>always</updatePolicy>
  </snapshots>
</repository>

**Comment by allengeary** [comment]
```
<repository>
  <id>xframium</id>
  <name>xFramium</name>
  <url>http://www.xframium.org/repository</url>
  <snapshots>
    <enabled>true</enabled>
    <updatePolicy>always</updatePolicy>
  </snapshots>
</repository>
```

**Comment by JocelynLiu** [comment]
yes, pom.xml has xFramium repository.  Eventually I found the issue and resolved it.  The problem is maven downloaded a broken xframium-serization-XXX.jar.  It looks like the jar is there, but it cannot be read properly.

I am curious if we search this jar by google it, why we cannot get anything as searched results?  This made me question if the jar is not in public central maven repository any more.

**Comment by JocelynLiu** [comment]
This issue could be closed as invalid.  
It would be great if anyone could have a check regarding maven central repository.  If any user has similar error, they might do the same thing as me--- first google it to see if pom.xml is correct, if they cannot find anything by google, they might start doubting if the repository is still there or not.  The next action they might do is either giving up xFramium, or report invalid defect. LOL
