### ISSUE TITLE
Issues with EXISTS keyword

### ISSUE THREAD

**Issue by ManasBBSR** [xframium/xframium-java#77]
The Exists keyword throws exception when more than 1 element are found.

Error message: returned multiple values while 1 was expected

Secondly if there is exactly 1 element it does not set the count in the context.

Code snippet of EXISTS keyword.
 
            if ( getContext() != null )
            {
                int elementCount = currentElement.getCount();
    
                if ( elementCount > 1 )
                {
                    if ( log.isDebugEnabled() )
                        log.debug( "Setting Context Data to [" + currentElement.getValue() + "] for [" + getContext() + "]" );
                    contextMap.put( getContext() + "_count", elementCount + "" );
                }
    
                if ( log.isDebugEnabled() )
                    log.debug( "Setting Context Data to [" + currentElement.getValue() + "] for [" + getContext() + "]" );
                addContext( getContext(), currentElement.getValue(), contextMap, executionContext );
            }

**Comment by xframium** [comment]
Selenium made a change to allow multiple elements found to be trimmed and returned as the single element on the list.  99% of the time and xPath returning multiple elements is an error and it was being hidden by that feature as end users would not know the element that they are working on.  We handled this by having users handle all element lists via the loop keyword however I remember in this case that you needed to do some logic up front.  We will investigate and determine a way to implement without breaking the current functinality

**Comment by ManasBBSR** [comment]
The example that I have is when I have to get the number of rows in a table I will use a common xpath or css and get the count of records and based on that perform some other operations which we have in our case. Because of the issue I'm not able to iterate through the rows unless I change some thing and have work around to loop through the results.

**Comment by xframium** [comment]
Resolved in 1.0.19
